spring:
  application:
    name: orchestrator-service
  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      teste: teste
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

server:
  port: 8080

logging:
  level:
    org:
      apache:
        kafka: OFF