server:
  port: 8092

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      inventory-success: inventory-success
      inventory-fail: inventory-fail
    consumer:
      group-id: payment-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:inventory-db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        boot:
          allow_jdbc_metadata_access: false

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: OFF
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLogger: OFF